<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            // ================= 1. ACADEMIC CONCEPTS (3 Projects) =================
            [
                'title' => 'The Eco-Study Pavilion & Timber Atrium',
                'slug' => 'the-eco-study-pavilion-timber-atrium',
                'category' => 'Academic Concepts',
                'subtitle' => 'ACADEMIC PROJECT',
                'client' => 'University Architecture Thesis',
                'location' => 'Cambridge, UK',
                'year' => 2026,
                'area_sqm' => '320 m²',
                'overview' => 'An academic thesis project exploring timber joinery, passive solar heating, and biophilic study spaces.',
                'concept_design' => 'Modeled in Rhino and SketchUp. Focuses on natural light penetration and timber construction details.',
                'sustainability_specs' => 'Spatial Planning • Architectural Concept • 3D Visualisation',
                'hero_image' => 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'ACADEMIC PROJECT',
                    'Scope of Work' => 'Spatial Planning • Architectural Concept • 3D Visualisation',
                    'Tools Used' => 'AutoCAD, SketchUp, V-Ray, Photoshop',
                ],
                'featured' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'The Biophilic Courtyard Concept',
                'slug' => 'the-biophilic-courtyard-concept',
                'category' => 'Academic Concepts',
                'subtitle' => 'ACADEMIC PROJECT',
                'client' => 'Student Architecture Showcase',
                'location' => 'London, UK',
                'year' => 2025,
                'area_sqm' => '210 m²',
                'overview' => 'A student project exploring biophilic garden infills and natural light penetration in urban courtyards.',
                'concept_design' => 'Designed to study living wall integration and skylight dome construction.',
                'sustainability_specs' => 'Concept Design • 3D Render • Environmental Study',
                'hero_image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'ACADEMIC PROJECT',
                    'Scope of Work' => 'Concept Design • 3D Render • Environmental Study',
                ],
                'featured' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'Parametric Timber Joinery Canopy Thesis',
                'slug' => 'parametric-timber-joinery-canopy-thesis',
                'category' => 'Academic Concepts',
                'subtitle' => 'ACADEMIC PROJECT',
                'client' => 'University Competition Entry',
                'location' => 'Bath, UK',
                'year' => 2026,
                'area_sqm' => '180 m²',
                'overview' => 'Computational Grasshopper parametric modeling exploring interlocking glulam timber joints and roof shadows.',
                'concept_design' => 'Algorithmic structural exploration optimizing sun trajectory and natural ventilation.',
                'sustainability_specs' => 'Parametric CAD • Structural Modeling • 3D Visualisation',
                'hero_image' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'ACADEMIC PROJECT',
                    'Scope of Work' => 'Parametric CAD • Structural Modeling • 3D Visualisation',
                ],
                'featured' => false,
                'sort_order' => 3,
            ],

            // ================= 2. 2D FLOOR PLANS (3 Projects) =================
            [
                'title' => 'Mayfair Townhouse Loft Conversion',
                'slug' => 'mayfair-townhouse-loft-conversion',
                'category' => '2D Floor Plans',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Private Client',
                'location' => 'Mayfair, London',
                'year' => 2025,
                'area_sqm' => '145 m²',
                'overview' => 'Precise 2D CAD floor plan survey and spatial layout drawings for a townhouse loft conversion.',
                'concept_design' => 'Laser survey measurements converted into clear CAD floor plans for planning permission.',
                'sustainability_specs' => 'Laser CAD Survey • 2D Floor Plan • Planning Layout',
                'hero_image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Laser CAD Survey • 2D Floor Plan • Space Planning',
                    'Delivery' => 'Scale PDF & DWG Drawings',
                ],
                'featured' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'Kensington Property Lease Plan',
                'slug' => 'kensington-property-lease-plan',
                'category' => '2D Floor Plans',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Property Landlord',
                'location' => 'Kensington, London',
                'year' => 2025,
                'area_sqm' => '180 m²',
                'overview' => 'Prepared in accordance with HM Land Registry requirements, featuring Ordnance Survey location map and demised boundaries.',
                'concept_design' => 'Accurate CAD demised boundary drawing for lease registration.',
                'sustainability_specs' => 'HM Land Registry Requirements • OS Location Plan • Demised Boundaries',
                'hero_image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Lease Plan • OS Location Map • Boundary Mapping',
                ],
                'featured' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Chelsea Apartment Ground Floor CAD Survey',
                'slug' => 'chelsea-apartment-ground-floor-cad-survey',
                'category' => '2D Floor Plans',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Interior Designer',
                'location' => 'Chelsea, London',
                'year' => 2026,
                'area_sqm' => '115 m²',
                'overview' => 'Detailed 1:50 scale floor plan mapping load-bearing walls, drainage connections, and electric sockets.',
                'concept_design' => 'Full measured survey converted into layer-separated AutoCAD floor plans.',
                'sustainability_specs' => 'Measured Building Survey • 2D CAD Drawings • Electrical Plan',
                'hero_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Measured Building Survey • 2D CAD Drawings • Electrical Plan',
                ],
                'featured' => false,
                'sort_order' => 6,
            ],

            // ================= 3. 3D VISUALISATIONS (3 Projects) =================
            [
                'title' => 'Soho Artisan Coffee & Work Studio',
                'slug' => 'soho-artisan-coffee-work-studio',
                'category' => '3D Visualisations',
                'subtitle' => 'PERSONAL CONCEPT PROJECT',
                'client' => 'Design Exploration',
                'location' => 'Soho, London',
                'year' => 2026,
                'area_sqm' => '120 m²',
                'overview' => 'A personal design concept exploring warm timber finishes, lighting, and interior layout options for a coffee bar.',
                'concept_design' => '3D interior modeling and material study developed to practice commercial lighting renders.',
                'sustainability_specs' => '3D Spatial Visualisation • Lighting Design • Material Study',
                'hero_image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'PERSONAL CONCEPT PROJECT',
                    'Scope of Work' => '3D Spatial Visualisation • Lighting Design • Interior Layout',
                    'Software' => 'SketchUp, V-Ray, Photoshop',
                ],
                'featured' => true,
                'sort_order' => 7,
            ],
            [
                'title' => 'Cambridge Villa Rear Extension Visualisation',
                'slug' => 'cambridge-villa-rear-extension-visualisation',
                'category' => '3D Visualisations',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Private Homeowner',
                'location' => 'Cambridge, UK',
                'year' => 2025,
                'area_sqm' => '95 m²',
                'overview' => '3D exterior render showing how a proposed glass rear extension integrates with a traditional brick villa.',
                'concept_design' => 'Helped homeowners explore daylight penetration and zinc roof finishes before starting build.',
                'sustainability_specs' => '3D Exterior Render • Material Options • Visualisation',
                'hero_image' => 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => '3D Exterior Render • Daylight Study • Visualisation',
                ],
                'featured' => false,
                'sort_order' => 8,
            ],
            [
                'title' => 'Modern Minimalist Kitchen & Living Spatial Render',
                'slug' => 'modern-minimalist-kitchen-living-spatial-render',
                'category' => '3D Visualisations',
                'subtitle' => 'DESIGN CONCEPT',
                'client' => 'Residential Remodel',
                'location' => 'Richmond, London',
                'year' => 2026,
                'area_sqm' => '85 m²',
                'overview' => 'Photorealistic 3D room render visualizing custom kitchen joinery, microcement flooring, and natural skylighting.',
                'concept_design' => 'High-detail V-Ray interior render showing daytime vs evening artificial lighting setups.',
                'sustainability_specs' => '3D Interior Modeling • Lighting Render • Joinery Detail',
                'hero_image' => 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'DESIGN CONCEPT',
                    'Scope of Work' => '3D Interior Modeling • Lighting Render • Joinery Detail',
                ],
                'featured' => false,
                'sort_order' => 9,
            ],

            // ================= 4. CLIENT PROJECTS (3 Projects) =================
            [
                'title' => 'Belgravia Residence Architectural Interior Elevation',
                'slug' => 'belgravia-residence-architectural-interior-elevation',
                'category' => 'Client Projects',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Luxury Interior Designer',
                'location' => 'Belgravia, London',
                'year' => 2025,
                'area_sqm' => '240 m²',
                'overview' => 'Full suite of CAD floor plans, wall elevations, and joinery workshop drawings for a Grade II listed property.',
                'concept_design' => 'Precision drawings respecting historical plasterwork while introducing contemporary built-in storage.',
                'sustainability_specs' => 'Interior CAD Elevations • Joinery Specs • Spatial Layout',
                'hero_image' => 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Interior CAD Elevations • Joinery Specs • Spatial Layout',
                ],
                'featured' => false,
                'sort_order' => 10,
            ],
            [
                'title' => 'Shoreditch Commercial Office Lease Boundary Plan',
                'slug' => 'shoreditch-commercial-office-lease-boundary-plan',
                'category' => 'Client Projects',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Commercial Landlord',
                'location' => 'Shoreditch, London',
                'year' => 2026,
                'area_sqm' => '350 m²',
                'overview' => 'Land Registry compliant lease plan for multi-tenant commercial office demise with shared circulation areas.',
                'concept_design' => 'Color-coded PG40 compliant demised boundary mapping.',
                'sustainability_specs' => 'Lease Registration Plan • Commercial Demise • Boundary Mapping',
                'hero_image' => 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Lease Registration Plan • Commercial Demise • Boundary Mapping',
                ],
                'featured' => false,
                'sort_order' => 11,
            ],
            [
                'title' => 'Oxfordshire Country Cottage Rear Glass Extension',
                'slug' => 'oxfordshire-country-cottage-rear-glass-extension',
                'category' => 'Client Projects',
                'subtitle' => 'CLIENT PROJECT',
                'client' => 'Private Homeowner',
                'location' => 'Oxfordshire, UK',
                'year' => 2025,
                'area_sqm' => '160 m²',
                'overview' => 'Planning application package comprising existing & proposed 2D elevations, floor plans, and 3D visual renders.',
                'concept_design' => 'Harmonious glass link connecting period stone cottage to open-plan kitchen dining space.',
                'sustainability_specs' => 'Planning Drawings • 2D Elevations • 3D Render',
                'hero_image' => 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?q=80&w=1600&auto=format&fit=crop',
                'blueprint_image' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
                'specifications' => [
                    'Project Classification' => 'CLIENT PROJECT',
                    'Scope of Work' => 'Planning Drawings • 2D Elevations • 3D Render',
                ],
                'featured' => false,
                'sort_order' => 12,
            ],
        ];

        foreach ($projects as $proj) {
            Project::updateOrCreate(['slug' => $proj['slug']], $proj);
        }
    }
}
